### ISSUE TITLE
Showing "Nan" instead of 0

### ISSUE THREAD

**Issue by HexaSayak** [ghoshsanjeev/calculator#6]
after typing any digit or noting into Dashboard, if we press EQUAL(=) it shows "NaN" as an Output instead of showing Zero (0) or That user input number
Steps:
1. Do nothing, just click on Equal(=) button
2. Or you can press any number & then press Equal(=)

Expected:
1. If no other input is in the Dashboard then it will show Zero (0)
2. If any number is already present in the dashboard, then it'll show that Number only.

Current:
"Nan" is showing instead of 0 or input value or result.

**Comment by ghoshsanjeev** [comment]
https://github.com/ghoshsanjeev/calculator/assets/5227589/6db7bb1a-cbb9-4c7e-bda5-af490a456c3e
